// <auto-generated />
namespace Pizza_Maker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class identfix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(identfix));
        
        string IMigrationMetadata.Id
        {
            get { return "201810252140139_identfix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
